version: '3'
services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_development
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
  test_database:
    image: 'postgres'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_test
    ports:
      - 5433:5432
    expose:
      - 5433
volumes:
  database-data:
